services:
  oracle:
    image: gvenzl/oracle-xe:21-slim
    container_name: oracle-xe
    ports:
      - "1521:1521"
    environment:
      - ORACLE_PASSWORD=password
      - APP_USER=admin
      - APP_USER_PASSWORD=password
    volumes:
      - ./src/SimpleCliApp/setup:/container-entrypoint-initdb.d
    healthcheck:
      test: ["CMD", "sqlplus", "-L", "admin/password@//localhost:1521/XEPDB1", "AS", "SYSDBA"]
      interval: 30s
      timeout: 10s
      retries: 5

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: csharp-app
    depends_on:
      oracle:
        condition: service_healthy
    environment:
      - ORACLE_CONNECTION=Data Source=oracle:1521/XEPDB1;User Id=admin;Password=password;

volumes:
  oracle-data:
